### ISSUE TITLE
Ratelimit Warning is blocking

### ISSUE THREAD

**Issue by XenonPy** [mojidev-py/discmoji#11]
What I mean by this is that because you're calling it with `raise`, it stops the program. We need to use `warnings.warn()`

self-assigned this, currently working on it

**Comment by XenonPy** [comment]
Fixed with PR.

**Comment by almostDemoPy** [comment]
you can use the ` Exception ` object catched by the ` except ` statement and have it processed by your ` warning.warn() ` or ` warning.error() ` method, whichever :
```py
try:
  raise NotImplemented("test")
except Exception as error:
  warning.error(error)
```

**Comment by XenonPy** [comment]
This seems more pythonic, could you fork this and make the changes (if you have time im really busy rn)? I can make a PR

**Comment by almostDemoPy** [comment]
@XenonPy regards this, you can take a look at my library's own logging module. ` Logger.error() ` requires an ` Exception ` object passed as parameter
