### ISSUE TITLE
BotIntents.default() == BotIntents.all() ?

### ISSUE THREAD

**Issue by almostDemoPy** [mojidev-py/discmoji#29]
why does ` classmethod BotIntents.default() ` contain almost all intents, including privileged ones ?
```py
class BotIntents:
  @classmethod
  def default(cls) -> Self:
    return ... | Intent.MESSAGE_CONTENT | ...
```

**Comment by mojidev-py** [comment]
Yeah, i think I might change that into `.all()`, because default @XenonPy put the privileged intents, but ty i completely didn't notice

**Comment by XenonPy** [comment]
My bad... totally forgot that was the default one lol

**Comment by mojidev-py** [comment]
> My bad... totally forgot that was the default one lol

no worries, everybody makes mistakes lol
