### ISSUE TITLE
Code Review #1

### ISSUE THREAD

**Issue by almostDemoPy** [mojidev-py/discmoji#4]
[` discmoji/bot.py | Lines 70 - 78 `](https://github.com/mojidev-py/discmoji/blob/95073fa12a6c90f0d7ab4170059aaae9785bf405/discmoji/bot.py#L70-L78)
```py
    async def get_guild(self,id: int) -> Guild:
        """Gets a guild from the bot's current joined guilds, through the id."""
        check = None
        for guild in self._guild_cache:
            if guild.id == id:
                check = True
                return guild
        if check is None:
            guild = Guild(asyncio.run(self._http.send_request('get',f"/guilds/{id}")).data)
```
so this is both cache and API call ? ` check ` variable is redundant here. ` return ` keyword exterminates the function's process and returns the value from whatever in the statement is. so this can be done with just : 
```py
for guild in self._guild_cache:
  if guild.id == id:
    return guild
return Guild(...)
```

---

[` discmoji/guild.py | Line 10 `](https://github.com/mojidev-py/discmoji/blob/95073fa12a6c90f0d7ab4170059aaae9785bf405/discmoji/guild.py#L10)
```py
class Guild:
  def __init__(self, ...) -> None:
    self.invoked : Optional[Invoked] = inboked
```
a guild object will have an ` Invoked ` object ? assuming your ` Invoke ` command has a ` guild ` attribute, this is blunder

---

[` discmoji/guild.py | Line 41 `](https://github.com/mojidev-py/discmoji/blob/95073fa12a6c90f0d7ab4170059aaae9785bf405/discmoji/guild.py#L41)
```py
class Guild:
  def get_member(self, username) -> Member:
    for member in self._member_cache:
      if member.nick == username:
        return member
```
` nick ` attribute can be different, no ?

---

[` discmoji/http.py | Lines 22 - 51 `](https://github.com/mojidev-py/discmoji/blob/95073fa12a6c90f0d7ab4170059aaae9785bf405/discmoji/http.py#L22-L51)
```py
class EndpointManager:
  async def send_request(
    self,
    method : Literal[...]
    route : str
  ) -> Payload:
    ...
```
what i had in mine was another enum lmao, but this one's good too. what i have is : 
```py
class GET(Enum):
  something = lambda var: return var

>>> test = GET.something("hello world")
>>> test
"hello world"
``` 
this allows me to just pass the variables and return the endpoint together with the variables, i don't have to type long :P 

---

[` discmoji/types.py | Line 102 `](https://github.com/mojidev-py/discmoji/blob/95073fa12a6c90f0d7ab4170059aaae9785bf405/discmoji/types.py#L102)
```py
class PermissionsBits(Enum):
  CREATE_INSTANT_INVITE = ...
```
just use bitwise left shifts lol ( or ` 2 ** n ` )

**Comment by XenonPy** [comment]
Yeah, I wasn't too sure about the check = None either

**Comment by mojidev-py** [comment]
ok! ty for the advice, and I didn't want to use the id attr, since guild member objects (through message create events) don't provide the user's id, but i'll edit that

**Comment by almostDemoPy** [comment]
i'll probably do this on mine too but you can utilize the ` joined_at ` ISO 8601 timestamp and convert it into a UNIX timestamp, and use the UNIX timestamp to query from your cache ( assuming the one in your cache will also have a non-empty ` user ` attribute )
```py
member.user : User = cache.query(joined_at = datetime.fromisoformat(joined_at)).user
```

References :
[` datetime.datetime.fromisoformat() `](<https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat>)

**Comment by mojidev-py** [comment]
> i'll probably do this on mine too but you can utilize the `joined_at` ISO 8601 timestamp and convert it into a UNIX timestamp, and use the UNIX timestamp to query from your cache ( assuming the one in your cache will also have a non-empty `user` attribute )
> 
> ```python
> member.user : User = cache.query(joined_at = datetime.fromisoformat(joined_at)).user
> ```
> 
> References : [`datetime.datetime.fromisoformat()`](https://docs.python.org/3/library/datetime.html#datetime.datetime.fromisoformat)

thank you for the help! I'll use it when i am working on guild members that actually have User attributes.

**Comment by almostDemoPy** [comment]
by the way. i cloned the repository yesterday to test something out for your behalf, and I received an error regarding ` types.py ` file. It seems, that on my end, I may have another global ` types ` module, resulting in a circular import. Though I've fixed this by just basically renaming it to` enums.py ` ( similar to what I had in mine )
