### ISSUE TITLE
Docstrings are missing

### ISSUE THREAD

**Issue by XenonPy** [mojidev-py/discmoji#5]
Functions appear to have comments describing what they do...
```python
def do_something(x):
     # this does something
     run code
     more code
```

However, as specified in PEP 257, these should be formatted as docstrings:
```python
def do_something(x):
     """
     This does something.
     """
     run code
     more code
```

https://peps.python.org/pep-0257/

**Comment by mojidev-py** [comment]
most of those commented functions are meant to be internal

**Comment by mojidev-py** [comment]
since they have an underscore before their name

**Comment by XenonPy** [comment]
oops 😅

yeah i missed that
